name: spotify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg:
  flutter_bloc:
  hydrated_bloc:
  path_provider:
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500 
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400 
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300 
